/**
 * Generator for customized Drizzle GritQL plugin files.
 *
 * This module generates GritQL plugin content with optional object name filtering,
 * similar to the ESLint plugin's `drizzleObjectName` option.
 */

export interface GeneratePluginOptions {
  /**
   * Array of Drizzle object names to match against.
   * When provided, rules will only trigger when the receiver object
   * matches one of these names, reducing false positives.
   *
   * Example: ['db', 'tx', 'database']
   */
  objectNames?: string[];

  /**
   * Whether to include the delete rule.
   * @default true
   */
  includeDeleteRule?: boolean;

  /**
   * Whether to include the update rule.
   * @default true
   */
  includeUpdateRule?: boolean;
}

/**
 * Generates the GritQL pattern for matching object names.
 * If no object names are provided, matches any object.
 */
function generateObjectPattern(objectNames: string[] | undefined): string {
  if (!objectNames || objectNames.length === 0) {
    return "$obj";
  }

  if (objectNames.length === 1) {
    return `\`${objectNames[0]}\``;
  }

  // Generate an "or" pattern for multiple object names
  const patterns = objectNames.map((name) => `\`${name}\``).join(", ");
  return `or { ${patterns} }`;
}

/**
 * Generates the enforce-delete-with-where rule pattern body.
 */
function generateDeleteRuleBody(objectNames: string[] | undefined): string {
  const objPattern = generateObjectPattern(objectNames);
  const objDescription = objectNames?.length
    ? `Drizzle object (${objectNames.join(", ")})`
    : "any object";

  // If we have specific object names, we need a different pattern structure
  if (objectNames && objectNames.length > 0) {
    return `    // Rule: drizzle/enforce-delete-with-where
    // Configured to match: ${objDescription}
    \`$obj.delete($args)\` as $call where {
        $obj <: ${objPattern},
        not $call <: within \`$_.where($_)\`,
        register_diagnostic(
            span = $call,
            message = "[drizzle/enforce-delete-with-where] Missing .where() clause. Calling .delete() without .where() will delete all rows in the table. Use db.delete(table).where(...) instead.",
            severity = "error"
        )
    }`;
  }

  return `    // Rule: drizzle/enforce-delete-with-where
    // Configured to match: ${objDescription}
    \`$obj.delete($args)\` as $call where {
        not $call <: within \`$_.where($_)\`,
        register_diagnostic(
            span = $call,
            message = "[drizzle/enforce-delete-with-where] Missing .where() clause. Calling .delete() without .where() will delete all rows in the table. Use db.delete(table).where(...) instead.",
            severity = "error"
        )
    }`;
}

/**
 * Generates the enforce-update-with-where rule pattern body.
 */
function generateUpdateRuleBody(objectNames: string[] | undefined): string {
  const objPattern = generateObjectPattern(objectNames);
  const objDescription = objectNames?.length
    ? `Drizzle object (${objectNames.join(", ")})`
    : "any object";

  // If we have specific object names, we need a different pattern structure
  if (objectNames && objectNames.length > 0) {
    return `    // Rule: drizzle/enforce-update-with-where
    // Configured to match: ${objDescription}
    \`$obj.update($table).set($values)\` as $call where {
        $obj <: ${objPattern},
        not $call <: within \`$_.where($_)\`,
        register_diagnostic(
            span = $call,
            message = "[drizzle/enforce-update-with-where] Missing .where() clause. Calling .update().set() without .where() will update all rows in the table. Use db.update(table).set(...).where(...) instead.",
            severity = "error"
        )
    }`;
  }

  return `    // Rule: drizzle/enforce-update-with-where
    // Configured to match: ${objDescription}
    \`$obj.update($table).set($values)\` as $call where {
        not $call <: within \`$_.where($_)\`,
        register_diagnostic(
            span = $call,
            message = "[drizzle/enforce-update-with-where] Missing .where() clause. Calling .update().set() without .where() will update all rows in the table. Use db.update(table).set(...).where(...) instead.",
            severity = "error"
        )
    }`;
}

/**
 * Generates a complete GritQL plugin file with the specified options.
 */
export function generatePlugin(options: GeneratePluginOptions = {}): string {
  const {
    objectNames,
    includeDeleteRule = true,
    includeUpdateRule = true,
  } = options;

  const header = [
    "engine biome(1.0)",
    "language js",
    "",
    "// Generated by biome-plugin-drizzle",
    `// Object filter: ${objectNames?.length ? objectNames.join(", ") : "none (matches all)"}`,
    "",
  ];

  const ruleBodies: string[] = [];

  if (includeDeleteRule) {
    ruleBodies.push(generateDeleteRuleBody(objectNames));
  }

  if (includeUpdateRule) {
    ruleBodies.push(generateUpdateRuleBody(objectNames));
  }

  // If we have multiple rules, wrap them in or {}
  if (ruleBodies.length === 0) {
    return `${header.join("\n")}// No rules enabled\n`;
  }

  if (ruleBodies.length === 1) {
    // Single rule - no need for or {} wrapper
    const singleRule = ruleBodies[0].replace(/^ {4}/gm, "");
    return `${header.join("\n") + singleRule}\n`;
  }

  // Multiple rules - wrap in or {}
  return `${header.join("\n")}or {\n${ruleBodies.join(",\n")}\n}\n`;
}
